name: Extlibs

on:
  push:
    branches: [ '!*' ]
  pull_request:
    branches: [ '!*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: update
        run: |
          #lua
          #cd ..
          #git clone https://github.com/NPI-D7/BCSTM-Player.git
          #cd Paint3ds
          #mkdir -p app/
          #mkdir -p extlibs/lua/
          #cp -r ../BCSTM-Player/app/* app/
          #cp -r ../lua/*.h* extlibs/lua/
          #cp -r ../lua/*.md extlibs/lua/
          #RenderD7
          cd ..
          git clone https://github.com/NPI-D7/RenderD7.git
          cd Terri-Fried
          mkdir -p RenderD7
          #rm -r extlibs/RenderD7
          mkdir -p RenderD7/
          cp -r ../RenderD7/* RenderD7/
          #cp -r ../RenderD7/*.h* extlibs/RenderD7/
          #cp -r ../RenderD7/*.md extlibs/RenderD7/
          #config
          git config --global user.email "tobid7@outlook.de"
          git config --global user.name "Tobi-D7"
          #commit
          git stage *
          git commit -m "update extlibs"
          git push origin main
